---
title: "p8105_hw1_sz2872"
author: "Shunyi Zhang"
date: "9/15/2020"
output: github_document
---

This is my solusion to hw1. 

```{r}
library(tidyverse)
library(tibble)
library(dplyr)
```

## Problem 1

Create a data frame with the specified elements. 

```{r creat_df}
prob1_df = 
  tibble(
    vec_num = rnorm(10),
    vec_log = vec_num > 0,
    vec_char = c("my", "cat", "names", "potato", "coke", "cola", "is", "a", "black", "kitty"),
    vec_factor = factor(c("small", "small", "small", "mid", "mid", "mid", "mid", "large", "large", "large"))
  )

prob1_df
```

Take the mean of each variable in my data frame.

```{r mean_df}
mean(pull(prob1_df, vec_num))
mean(pull(prob1_df, vec_log))
mean(pull(prob1_df, vec_char))
mean(pull(prob1_df, vec_factor))
```

I can take the mean for the numbers and logical but not for the character or factor. 

Convert vectors to numeric.

```{r convert_vec, eval = FALSE}
as.numeric(pull(prob1_df, vec_log))
as.numeric(pull(prob1_df, vec_char))
as.numeric(pull(prob1_df, vec_factor))
```

